// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package go_usermgmt_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserManagenentClient is the client API for UserManagenent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserManagenentClient interface {
	CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type userManagenentClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagenentClient(cc grpc.ClientConnInterface) UserManagenentClient {
	return &userManagenentClient{cc}
}

func (c *userManagenentClient) CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/usermgmt.UserManagenent/CreateNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagenentServer is the server API for UserManagenent service.
// All implementations must embed UnimplementedUserManagenentServer
// for forward compatibility
type UserManagenentServer interface {
	CreateNewUser(context.Context, *NewUser) (*User, error)
	mustEmbedUnimplementedUserManagenentServer()
}

// UnimplementedUserManagenentServer must be embedded to have forward compatible implementations.
type UnimplementedUserManagenentServer struct {
}

func (UnimplementedUserManagenentServer) CreateNewUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewUser not implemented")
}
func (UnimplementedUserManagenentServer) mustEmbedUnimplementedUserManagenentServer() {}

// UnsafeUserManagenentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserManagenentServer will
// result in compilation errors.
type UnsafeUserManagenentServer interface {
	mustEmbedUnimplementedUserManagenentServer()
}

func RegisterUserManagenentServer(s grpc.ServiceRegistrar, srv UserManagenentServer) {
	s.RegisterService(&UserManagenent_ServiceDesc, srv)
}

func _UserManagenent_CreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagenentServer).CreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgmt.UserManagenent/CreateNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagenentServer).CreateNewUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

// UserManagenent_ServiceDesc is the grpc.ServiceDesc for UserManagenent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserManagenent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermgmt.UserManagenent",
	HandlerType: (*UserManagenentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewUser",
			Handler:    _UserManagenent_CreateNewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermgmt/usermgmt.proto",
}
